slam_toolbox:
  ros__parameters:
    use_sim_time: true
    map_frame: map
    odom_frame: odom
    base_frame: base_footprint
    scan_topic: /scan
    use_laser_scan: true
    use_laser_scan_multi: false
    max_laser_range: 3.5
    min_laser_range: 0.12
    resolution: 0.05
    mode: mapping
